### PR TITLE
David

### PR DESCRIPTION
**Pull request by dreko1**
Added a new card, this is a potential way to format when we have more than one listing.

### CODE REVIEW

**Comment by ndiekema** [comment]
Looks good!

**Comment by dreko1** [comment]
@ndiekema Thanks!

**Comment by Cheeems** [comment]
Looks good to me. One thing that we should look into is some material-UI component that makes the cards look cleaner.

**Comment by dreko1** [comment]
@Cheeems Thanks for the response. I feel that same way, it doesn't render on the page exactly how we had previously discussed it. I am looking into a cleaner solution right now!

**Comment by Chris-Middleton** [comment]
Sounds good, we need to have more than a page worth of posts though lol

**Comment by dreko1** [comment]
@Chris-Middleton True, everything will likely be a little different when things get scaled up!

**Pull request closed without merging**
