### PR TITLE
Create Listing incl. name, desc, img - Danveer

### PR DESCRIPTION
**Pull request by Cheeems**
Added create new listing feature that includes Item Name, description and image upload.

### CODE REVIEW

**Comment by dreko1** [comment]
This looks really good and I think that it is something that we can merge into the main branch!

**Comment by ndiekema** [comment]
Looks good to merge. Eventually we should have an option for the user to input all of the fields for a listing included in the backend. For instance: price, category (this should be a dropdown menu), location (state, city, zip).

**Comment by Chris-Middleton** [comment]
Okay cool, I think we need to have making a listing either show up on a new page, or replace the content pane, rather than having it float above the page like signin does.

**Comment by Cheeems** [comment]
> This looks really good and I think that it is something that we can merge into the main branch!

Thanks! I think eventually we can build on this and add some other cool features with listings.

**Comment by Cheeems** [comment]
> Looks good to merge. Eventually we should have an option for the user to input all of the fields for a listing included in the backend. For instance: price, category (this should be a dropdown menu), location (state, city, zip).

Great Idea! Would be good to do this in sprint 3!

**Comment by Cheeems** [comment]
> Okay cool, I think we need to have making a listing either show up on a new page, or replace the content pane, rather than having it float above the page like signin does.

Good suggestion! Will be adding this before end of sprint

**Pull request merged**
